### PR TITLE
basic integration testes on blog endpoint

### PR DESCRIPTION
**Pull request by MC-Knight**
#### What does this PR do?

This pull request aims to implement basic integration tests for the blog endpoints in the portfolio_api project.

#### Description of Task to be completed?

The task completed in this pull request includes writing tests for the following functionalities:
- Get all blogs
- Increase views number of a blog
- Increase likes number of a blog
- Edit request while not authorized (expected: 403)
- Delete a blog while not authorized (expected: 403)
- Edit a blog while not authorized (expected: 403)
- Get single blog

#### How should this be manually tested?

To manually test the changes made in this pull request, follow these steps:

```
git clone  https://github.com/MC-Knight/portfolio_api.git
cd portfolio_api
git checkout ft-api-docs?
npm i
set all environmental variable
npm run test
```

### CODE REVIEW

**Comment by faid-terence** [comment]
Hi @MC-Knight ! , _Can you please write a Pull Request_

**Review by faid-terence — CHANGES_REQUESTED** [review]
Please , Write a proper PR !

**Comment by faid-terence** [comment]
Also your commit message should be descriptive , like you should mention if it's either 
a feature, bug or chore !

**Comment by MC-Knight** [comment]
> Please , Write a proper PR !

i have tried this time, you can check

**Comment by faid-terence** [comment]
Nice Work @MC-Knight 
You can now re-request ! then i approve !

**Review by faid-terence — APPROVED** [review]

**Comment by faid-terence** [comment]
Done ! , You can now merge your PR!

**Comment by MC-Knight** [comment]
> Done ! , You can now merge your PR!

thank you

**Pull request merged**
